const subUserConstants = {
  GET_SUBUSERS_REQUEST: "GET_SUBUSER_REQUEST",
  GET_SUBUSERS_SUCCESS: "GET_SUBUSER_SUCCESS",
  GET_SUBUSERS_ERROR: "GET_SUBUSER_ERROR",

  DELETE_SUBUSERS_REQUEST: "DELETE_SUBUSERS_REQUEST",
  DELETE_SUBUSERS_SUCCESS: "DELETE_SUBUSERS_SUCCESS",
  DELETE_SUBUSERS_ERROR: "DELETE_SUBUSERS_ERROR",

  GET_SUBUSER_DATA_REQUEST: "GET_SUBUSER_DATA_REQUEST",
  GET_SUBUSER_DATA_SUCCESS: "GET_SUBUSER_DATA_SUCCESS",
  GET_SUBUSER_DATA_ERROR: "GET_SUBUSER_DATA_ERROR",

  GET_USER_PERMISSIONS_REQUEST: "GET_USER_PERMISSIONS_REQUEST",
  GET_USER_PERMISSIONS_SUCCESS: "GET_USER_PERMISSIONS_SUCCESS",
  GET_USER_PERMISSIONS_ERROR: "GET_USER_PERMISSIONS_ERROR",

  UPDATE_SUBUSER_DATA_REQUEST: "UPDATE_SUBUSER_DATA_REQUEST",
  UPDATE_SUBUSER_DATA_SUCCESS: "UPDATE_SUBUSER_DATA_SUCCESS",
  UPDATE_SUBUSER_DATA_ERROR: "UPDATE_SUBUSER_DATA_ERROR"
};

export default subUserConstants;
