export const jobListingConstants = {
  GET_JOBS_LIST_REQUEST: "GET_USER_EMAIL_REQUEST",
  GET_JOBS_LIST_SUCCESS: "GET_USER_EMAIL_SUCCESS",
  GET_JOBS_LIST_ERROR: "GET_USER_EMAIL_ERROR",

  SHARE_JOBS_REQUEST: "DELETE_ACCOUNT_REQUEST",
  SHARE_JOBS_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
  SHARE_JOBS_ERROR: "DELETE_ACCOUNT_ERROR",

  SAVED_JOBS_REQUEST: "REACTIVATE_ACCOUNT_REQUEST",
  SAVED_JOBS_SUCCESS: "REACTIVATE_ACCOUNT_SUCCESS",
  SAVED_JOBS_ERROR: "REACTIVATE_ACCOUNT_ERROR",
}
