const JOBSEEKER_FORM_REQUEST = "JOBSEEKER_FORM_REQUEST";
const JOBSEEKER_FORM_UPDATE_REQUEST = "JOBSEEKER_FORM_UPDATE_REQUEST";
const UPDATE_JOBSEEKER_SIGNUP_PERSONAL_DETAILS = "UPDATE_JOBSEEKER_SIGNUP_PERSONAL_DETAILS";
const UPDATE_JOBSEEKER_SIGNUP_EDUCATION_DETAILS = "UPDATE_JOBSEEKER_SIGNUP_EDUCATION_DETAILS";
const UPDATE_JOBSEEKER_SIGNUP_EMPLOYMENT_DETAILS = "UPDATE_JOBSEEKER_SIGNUP_EMPLOYMENT_DETAILS";

export {
  JOBSEEKER_FORM_REQUEST,
  JOBSEEKER_FORM_UPDATE_REQUEST,
  UPDATE_JOBSEEKER_SIGNUP_PERSONAL_DETAILS,
  UPDATE_JOBSEEKER_SIGNUP_EDUCATION_DETAILS,
  UPDATE_JOBSEEKER_SIGNUP_EMPLOYMENT_DETAILS,
};
