const JOBSEEKER_SIGNUP_REQUEST = "JOBSEEKER_SIGNUP_REQUEST";
const JOBSEEKER_SIGNIN_REQUEST = "JOBSEEKER_SIGNIN_REQUEST";
const GET_AUTOCOMPLETE_RESULTS = "GET_AUTOCOMPLETE_RESULTS";
const GET_AUTOCOMPLETE_RESULTS = "GET_AUTOCOMPLETE_RESULTS";

export {
    JOBSEEKER_SIGNUP_REQUEST,
    JOBSEEKER_SIGNIN_REQUEST,
    GET_AUTOCOMPLETE_RESULTS
};
