export const jobApplicationStatusConstants={
  GET_JOB_APPLICATION_LIST_REQUEST : "GET_JOB_APPLICATION_LIST_REQUEST",
  GET_JOB_APPLICATION_LIST_SUCCESS : "GET_JOB_APPLICATION_LIST_SUCCESS",
  GET_JOB_APPLICATION_LIST_ERROR : "GET_JOB_APPLICATION_LIST_ERROR",

  GET_JOB_APPLICATION_DATA_REQUEST : "GET_JOB_APPLICATION_DATA_REQUEST",
  GET_JOB_APPLICATION_DATA_SUCCESS : "GET_JOB_APPLICATION_DATA_SUCCESS",
  GET_JOB_APPLICATION_DATA_ERROR : "GET_JOB_APPLICATION_DATA_ERROR",
}
