export const accountSettingsConstants = {

  GET_USER_EMAIL_REQUEST: "GET_USER_EMAIL_REQUEST",
  GET_USER_EMAIL_SUCCESS: "GET_USER_EMAIL_SUCCESS",
  GET_USER_EMAIL_ERROR: "GET_USER_EMAIL_ERROR",

  DELETE_ACCOUNT_REQUEST: "DELETE_ACCOUNT_REQUEST",
  DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
  DELETE_ACCOUNT_ERROR: "DELETE_ACCOUNT_ERROR",

  REACTIVATE_ACCOUNT_REQUEST: "REACTIVATE_ACCOUNT_REQUEST",
  REACTIVATE_ACCOUNT_SUCCESS: "REACTIVATE_ACCOUNT_SUCCESS",
  REACTIVATE_ACCOUNT_ERROR: "REACTIVATE_ACCOUNT_ERROR",

  SUSPEND_ACCOUNT_REQUEST: "SUSPEND_ACCOUNT_REQUEST",
  SUSPEND_ACCOUNT_SUCCESS: "SUSPEND_ACCOUNT_SUCCESS",
  SUSPEND_ACCOUNT_ERROR: "SUSPEND_ACCOUNT_ERROR",

  CHANGE_ACCOUNT_PASSWORD_REQUEST: "CHANGE_ACCOUNT_PASSWORD_REQUEST",
  CHANGE_ACCOUNT_PASSWORD_SUCCESS: "CHANGE_ACCOUNT_PASSWORD_SUCCESS",
  CHANGE_ACCOUNT_PASSWORD_ERROR: "CHANGE_ACCOUNT_PASSWORD_ERROR",

  VALIDATE_OTP_REQUEST: "VALIDATE_OTP_REQUEST",
  VALIDATE_OTP_SUCCESS: "VALIDATE_OTP_SUCCESS",
  VALIDATE_OTP_ERROR: "VALIDATE_OTP_ERROR",

  SEND_OTP_REQUEST: "SEND_OTP_REQUEST",
  SEND_OTP_SUCCESS: "SEND_OTP_SUCCESS",
  SEND_OTP_ERROR: "SEND_OTP_ERROR",

  CHECK_EMAIL_AVAILABLE_REQUEST: "CHECK_EMAIL_AVAILABLE_REQUEST",
  CHECK_EMAIL_AVAILABLE_SUCCESS: "CHECK_EMAIL_AVAILABLE_SUCCESS",
  CHECK_EMAIL_AVAILABLE_ERROR: "CHECK_EMAIL_AVAILABLE_ERROR",

}
