export const UPDATE_EMP_BASIC_DETAILS = "UPDATE_EMP_BASIC_DETAILS";
export const UPDATE_EMP_CONTACT_DETAILS = "UPDATE_EMP_CONTACT_DETAILS";
export const UPDATE_EMP_WORK_EXP = "UPDATE_EMP_WORK_EXP";
export const UPDATE_SECTOR_ROLES_HIRE_FOR = "UPDATE_SECTOR_ROLES_HIRE_FOR";